/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

public class ProdutoListaPanel extends javax.swing.JPanel {

    LojaDados dados;
    List<Produto> listaProdutosSalvos;
    /**
     * Creates new form ProdutoListaPanel
     */
    public ProdutoListaPanel() {
        initComponents();
        listaProdutos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = lerProdutos();
            @Override
            public int getSize() { return strings.length; }
            @Override
            public String getElementAt(int i) { return strings[i]; }
        });
    }
    
    public String[] lerProdutos() {
        String[] produtos;
        dados = new LojaDados();
        
        try {
            listaProdutosSalvos = dados.recuperaProdutosDeArquivo();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro ao ler a lista de produtos!", JOptionPane.ERROR_MESSAGE);
            listaProdutosSalvos = new ArrayList();
        }
        
        produtos = new String[listaProdutosSalvos.size()];
        
        for (int i = 0; i < listaProdutosSalvos.size(); i++) {
            produtos[i] = listaProdutosSalvos.get(i).toString();            
        }
        
        return produtos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaProdutos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        listaProdutos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaProdutos);

        add(jScrollPane1);
        jScrollPane1.setBounds(40, 80, 327, 192);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Lista de Produtos");
        add(jLabel1);
        jLabel1.setBounds(120, 30, 180, 22);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaProdutos;
    // End of variables declaration//GEN-END:variables
}
