package projeto;

import java.awt.PopupMenu;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

public class ClienteListaPanel extends javax.swing.JPanel {

    LojaDados dados;
    List<Cliente> listaClientesSalvos;

    public ClienteListaPanel() {
        initComponents();
        listaClientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = lerClientes();
            @Override
            public int getSize() { return strings.length; }
            @Override
            public String getElementAt(int i) { return strings[i]; }
        });
    }
    
    public String[] lerClientes() {
        String[] clientes;
        dados = new LojaDados();
        
        try {
            listaClientesSalvos = dados.recuperaClientesDeArquivo();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro ao ler a lista de clientes!", JOptionPane.ERROR_MESSAGE);
            listaClientesSalvos = new ArrayList();
        }
        
        clientes = new String[listaClientesSalvos.size()];
        
        for (int i = 0; i < listaClientesSalvos.size(); i++) {
            clientes[i] = listaClientesSalvos.get(i).toString();            
        }
        
        return clientes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaClientes = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        listaClientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaClientes);

        add(jScrollPane1);
        jScrollPane1.setBounds(40, 80, 327, 192);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Lista de Clientes");
        add(jLabel1);
        jLabel1.setBounds(120, 30, 180, 22);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaClientes;
    // End of variables declaration//GEN-END:variables
}
