package views;

import models.Cliente;
import controllers.LojaVirtual;
import exceptions.ClienteExistente;
import javax.swing.JOptionPane;

public class ClienteCadastroPanel extends javax.swing.JDialog {

    private static Cliente cliente;
    private static LojaVirtual loja = LojaFrame.getLojaVirtual();
    /**
     * Creates new form ClienteCadastroPanel
     */
    public ClienteCadastroPanel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldBairro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textFieldNome = new javax.swing.JTextField();
        textFieldCPF = new javax.swing.JTextField();
        textFieldEndereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(textFieldBairro);
        textFieldBairro.setBounds(130, 190, 260, 30);

        jLabel2.setText("CPF");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 110, 60, 14);

        jLabel3.setText("Endereço");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 150, 60, 14);

        jLabel4.setText("Bairro");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 190, 60, 14);

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 70, 70, 14);
        getContentPane().add(textFieldNome);
        textFieldNome.setBounds(130, 70, 260, 30);
        getContentPane().add(textFieldCPF);
        textFieldCPF.setBounds(130, 110, 260, 30);
        getContentPane().add(textFieldEndereco);
        textFieldEndereco.setBounds(130, 150, 260, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Cadastro de Cliente");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 10, 200, 40);

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 250, 260, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nome = textFieldNome.getText();
        String cpf = textFieldCPF.getText();
        String endereco = textFieldEndereco.getText();
        String bairro = textFieldBairro.getText();
        
        if (!nome.isBlank() && !nome.isEmpty() && !cpf.isBlank() && !cpf.isEmpty()
                && !endereco.isBlank() && !endereco.isEmpty() && !bairro.isBlank() && !bairro.isEmpty()) {
            cliente = new Cliente(nome, cpf, endereco, bairro);
        
            try {
                if (cliente != null) {
                    loja.cadastrar(cliente);
                } else {
                    JOptionPane.showMessageDialog(null, "Os dados não foram preenchidos", "Não foi possível cadastrar o cliente", JOptionPane.ERROR_MESSAGE);
                }                       
            } catch (ClienteExistente ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }

            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteCadastroPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteCadastroPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteCadastroPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteCadastroPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            ClienteCadastroPanel dialog = new ClienteCadastroPanel(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField textFieldBairro;
    private javax.swing.JTextField textFieldCPF;
    private javax.swing.JTextField textFieldEndereco;
    private javax.swing.JTextField textFieldNome;
    // End of variables declaration//GEN-END:variables
}
