package views;

import controllers.LojaVirtual;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import models.Cliente;
import models.Produto;
import models.Venda;
public class LojaFrame extends javax.swing.JFrame {

    protected static LojaVirtual lojaVirtual = new LojaVirtual();
    
    private List<Produto> listaProdutosVenda = new ArrayList();
    private DefaultListModel<String> list = new DefaultListModel();
    private double total = 0;
    private Cliente clienteVenda;
    
    public LojaFrame() {
        initComponents();
        selectProdutos();
        selectClientes();
    }

    public static LojaVirtual getLojaVirtual() {
        return lojaVirtual;
    }
    
    public void selectProdutos() {
        String item = "(Selecionar)";
        selectProdutos.addItem(item);
        for (Produto produto : lojaVirtual.getProdutos()) {
            item = produto.getNome() + " - " + produto.getPreco();
            selectProdutos.addItem(item);
        }
    }
    
    public void selectClientes() {
        String item = "(Selecionar)";
        selectClientes.addItem(item);
        for (Cliente cliente : lojaVirtual.getClientes()) {
            item = cliente.getNome();
            selectClientes.addItem(item);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        selectProdutos = new javax.swing.JComboBox<>();
        selectClientes = new javax.swing.JComboBox<>();
        buttonInserirNaLista = new javax.swing.JButton();
        textQuantidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProdutosSelecionados = new javax.swing.JList<>();
        buttonFinalizarCompra = new javax.swing.JButton();
        labelClienteInfo = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuCadastroProduto = new javax.swing.JMenuItem();
        menuCadastroCliente = new javax.swing.JMenuItem();
        menuLista = new javax.swing.JMenu();
        menuListaProdutos = new javax.swing.JMenuItem();
        menuListaClientes = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Produto");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 90, 107, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Cliente");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 29, 84, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Quantidade");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 150, 130, 29);

        getContentPane().add(selectProdutos);
        selectProdutos.setBounds(150, 90, 143, 29);

        getContentPane().add(selectClientes);
        selectClientes.setBounds(150, 30, 143, 29);

        buttonInserirNaLista.setText("Inserir");
        buttonInserirNaLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInserirNaListaActionPerformed(evt);
            }
        });
        getContentPane().add(buttonInserirNaLista);
        buttonInserirNaLista.setBounds(20, 240, 286, 32);
        getContentPane().add(textQuantidade);
        textQuantidade.setBounds(150, 150, 146, 35);

        jScrollPane1.setViewportView(listaProdutosSelecionados);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(340, 50, 179, 130);

        buttonFinalizarCompra.setText("Finalizar Compra");
        buttonFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFinalizarCompraActionPerformed(evt);
            }
        });
        getContentPane().add(buttonFinalizarCompra);
        buttonFinalizarCompra.setBounds(340, 240, 179, 32);

        labelClienteInfo.setText("Produtos selecionados para ");
        getContentPane().add(labelClienteInfo);
        labelClienteInfo.setBounds(340, 30, 180, 14);
        getContentPane().add(labelCliente);
        labelCliente.setBounds(340, 30, 180, 0);

        labelTotal.setText("Total:");
        getContentPane().add(labelTotal);
        labelTotal.setBounds(340, 184, 180, 30);

        menuCadastro.setText("Cadastros");

        menuCadastroProduto.setText("Produto");
        menuCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroProdutoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroProduto);

        menuCadastroCliente.setText("Cliente");
        menuCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroClienteActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroCliente);

        jMenuBar1.add(menuCadastro);

        menuLista.setText("Dados");
        menuLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListaActionPerformed(evt);
            }
        });

        menuListaProdutos.setText("Listar Produtos");
        menuListaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListaProdutosActionPerformed(evt);
            }
        });
        menuLista.add(menuListaProdutos);

        menuListaClientes.setText("Listar Clientes");
        menuListaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListaClientesActionPerformed(evt);
            }
        });
        menuLista.add(menuListaClientes);

        jMenuItem1.setText("Listar Vendas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuLista.add(jMenuItem1);

        jMenuBar1.add(menuLista);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroProdutoActionPerformed
        ProdutoCadastroPanel form = new ProdutoCadastroPanel(this, true);
        form.setSize(480, 350);
        form.setLocationRelativeTo(this);
        form.setVisible(true);
    }//GEN-LAST:event_menuCadastroProdutoActionPerformed

    private void menuListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuListaActionPerformed

    private void menuListaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListaClientesActionPerformed
        ClienteListaPanel form = new ClienteListaPanel(this, true);
        form.setSize(430, 380);
        form.setLocationRelativeTo(this);
        form.setVisible(true);
    }//GEN-LAST:event_menuListaClientesActionPerformed

    private void menuListaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListaProdutosActionPerformed
        ProdutoListaPanel form = new ProdutoListaPanel(this, true);
        form.setSize(430, 380);
        form.setLocationRelativeTo(this);
        form.setVisible(true);
    }//GEN-LAST:event_menuListaProdutosActionPerformed

    private void menuCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroClienteActionPerformed
        ClienteCadastroPanel form = new ClienteCadastroPanel(this, true);
        form.setSize(430, 350);
        form.setLocationRelativeTo(this);
        form.setVisible(true);
    }//GEN-LAST:event_menuCadastroClienteActionPerformed

    private void buttonInserirNaListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInserirNaListaActionPerformed
        if (selectProdutos.getSelectedIndex() != 0 && selectClientes.getSelectedIndex() != 0) {
            String produto = (String) selectProdutos.getSelectedItem();
            String cliente = (String) selectClientes.getSelectedItem();
            String quantidade = textQuantidade.getText();
            
            if (!produto.isBlank() && !produto.isEmpty() && !cliente.isBlank() && !cliente.isEmpty() && !quantidade.isBlank() && !quantidade.isEmpty()) {
                clienteVenda = lojaVirtual.pesquisarCliente(cliente);

                String[] produtosInfo = produto.split("-");
                Produto p = lojaVirtual.pesquisarProduto(produtosInfo[0].trim());
                listaProdutosVenda.add(p);                

                total += Integer.parseInt(quantidade) * p.getPreco();

                labelTotal.setText("Total:" + " " + String.valueOf(total));
                labelClienteInfo.setText(labelClienteInfo.getText() + " " + cliente);

                list.addElement("Produto: " + produto + ", Quantidade: " + quantidade);

                listaProdutosSelecionados.setModel(list);
            } else {
                JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente e/ou produto!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonInserirNaListaActionPerformed

    private void buttonFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFinalizarCompraActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Finalizar a venda?", "Atenção!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (opcao == 0) {
            Venda v = new Venda();
            v.setCliente(clienteVenda);
            v.setProdutos(listaProdutosVenda);
            v.setTotal_pagar(total);

            lojaVirtual.getVendas().add(v);
            
            limparCampos();
        }
    }//GEN-LAST:event_buttonFinalizarCompraActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        VendaListaPanel form = new VendaListaPanel(this, true);
        form.setSize(430, 380);
        form.setLocationRelativeTo(this);
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void limparCampos() {
        list.removeAllElements();
        labelTotal.setText("Total:");
        labelClienteInfo.setText("Produtos selecionados para");
        textQuantidade.setText("");
        selectProdutos.setSelectedIndex(0);
        selectClientes.setSelectedIndex(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LojaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LojaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LojaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LojaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LojaFrame loja = new LojaFrame();
                loja.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    try {
                        //ao encerrar o programa, salva todas as listas do sistema
                        lojaVirtual.salvar();
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                    System.exit(0);
                }
            });
                loja.setLocationRelativeTo(null);
                loja.setSize(550, 350);
                loja.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFinalizarCompra;
    private javax.swing.JButton buttonInserirNaLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelClienteInfo;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JList<String> listaProdutosSelecionados;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuCadastroCliente;
    private javax.swing.JMenuItem menuCadastroProduto;
    private javax.swing.JMenu menuLista;
    private javax.swing.JMenuItem menuListaClientes;
    private javax.swing.JMenuItem menuListaProdutos;
    private javax.swing.JComboBox<String> selectClientes;
    private javax.swing.JComboBox<String> selectProdutos;
    private javax.swing.JTextField textQuantidade;
    // End of variables declaration//GEN-END:variables
}
