package views;

import controllers.LojaVirtual;
import exceptions.ProdutoExistente;
import javax.swing.JOptionPane;
import models.Produto;

public class ProdutoCadastroPanel extends javax.swing.JDialog {

    private static Produto produto;
    private static LojaVirtual loja = LojaFrame.getLojaVirtual();

    /**
     * Creates new form ProdutoCadastroPanel
     */
    public ProdutoCadastroPanel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textFieldName = new javax.swing.JTextField();
        textFieldPreco = new javax.swing.JTextField();
        textFieldQuantidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        buttonConfirmar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDescricao = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("Preço");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 110, 60, 14);

        jLabel3.setText("Quantidade em estoque");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 110, 120, 20);

        jLabel4.setText("Descrição");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 170, 60, 14);

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 50, 70, 14);
        getContentPane().add(textFieldName);
        textFieldName.setBounds(90, 70, 340, 30);
        getContentPane().add(textFieldPreco);
        textFieldPreco.setBounds(90, 130, 160, 30);
        getContentPane().add(textFieldQuantidade);
        textFieldQuantidade.setBounds(270, 130, 160, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Cadastro de Produto");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 10, 200, 40);

        buttonConfirmar.setText("Confirmar");
        buttonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonConfirmar);
        buttonConfirmar.setBounds(140, 250, 240, 40);

        textAreaDescricao.setColumns(20);
        textAreaDescricao.setRows(5);
        jScrollPane1.setViewportView(textAreaDescricao);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 190, 340, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmarActionPerformed
        /*
        Lê todas as informações dos campos da tela
        monta o objeto produto
        insere o objeto numa lista da tela principal
        */
        try {
            String nome = textFieldName.getText();
            double preco = Double.parseDouble(textFieldPreco.getText());
            int quantidade = Integer.parseInt(textFieldQuantidade.getText());
            String descricao = textAreaDescricao.getText();
            
            if (!nome.isBlank() && !nome.isEmpty() && !descricao.isBlank() && !descricao.isEmpty() && preco > 0 && quantidade > 0) {
                produto = new Produto(nome, preco, quantidade, descricao);

                try {
                    if (produto != null) {
                        loja.cadastrar(produto);
                    } else {
                        JOptionPane.showMessageDialog(null, "Os dados não foram preenchidos", "Não foi possível cadastrar o produto", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (ProdutoExistente ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                }

                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!", "Erro", JOptionPane.ERROR_MESSAGE);
            }    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_buttonConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoCadastroPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoCadastroPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoCadastroPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoCadastroPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            ProdutoCadastroPanel dialog = new ProdutoCadastroPanel(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaDescricao;
    private javax.swing.JTextField textFieldName;
    private javax.swing.JTextField textFieldPreco;
    private javax.swing.JTextField textFieldQuantidade;
    // End of variables declaration//GEN-END:variables
}
